dist: trusty
sudo: required
services:
- docker

env:
  matrix:
  - SUITE=artful
  - SUITE=bionic
  - SUITE=buster
  - SUITE=jessie
  - SUITE=sid
  - SUITE=stretch
  - SUITE=trusty
  - SUITE=xenial

branches:
  only: master

install:
- git clone --depth 1 -b krogoth git://git.yoctoproject.org/poky.git ${TRAVIS_BUILD_DIR%/${TRAVIS_REPO_SLUG}}/poky

script:
- docker build --tag vicamo/yocto:test $SUITE
- sudo chown -R $(docker run --rm vicamo/yocto:test id -u).$(docker run --rm vicamo/yocto:test id -g)
    ${TRAVIS_BUILD_DIR%/${TRAVIS_REPO_SLUG}}/poky
- docker run --rm
    --volume ${TRAVIS_BUILD_DIR%/${TRAVIS_REPO_SLUG}}/poky:/poky
    --workdir /poky
    vicamo/yocto:test
    /bin/bash -c "source oe-init-build-env; bitbake -h; bitbake automake-native"
